/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mahoni.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TripEnrichment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 797286282589555080L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TripEnrichment\",\"namespace\":\"com.mahoni.schema\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"tripId\",\"type\":\"string\"},{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"qrId\",\"type\":\"string\"},{\"name\":\"scan\",\"type\":\"string\"},{\"name\":\"status\",\"type\":\"string\"},{\"name\":\"sex\",\"type\":\"string\"},{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"location_name\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TripEnrichment> ENCODER =
      new BinaryMessageEncoder<TripEnrichment>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TripEnrichment> DECODER =
      new BinaryMessageDecoder<TripEnrichment>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TripEnrichment> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TripEnrichment> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TripEnrichment> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TripEnrichment>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TripEnrichment to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TripEnrichment from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TripEnrichment instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TripEnrichment fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private CharSequence eventId;
   private long timestamp;
   private CharSequence tripId;
   private CharSequence userId;
   private CharSequence qrId;
   private CharSequence scan;
   private CharSequence status;
   private CharSequence sex;
   private int age;
   private CharSequence location_name;
   private CharSequence type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TripEnrichment() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param timestamp The new value for timestamp
   * @param tripId The new value for tripId
   * @param userId The new value for userId
   * @param qrId The new value for qrId
   * @param scan The new value for scan
   * @param status The new value for status
   * @param sex The new value for sex
   * @param age The new value for age
   * @param location_name The new value for location_name
   * @param type The new value for type
   */
  public TripEnrichment(CharSequence eventId, Long timestamp, CharSequence tripId, CharSequence userId, CharSequence qrId, CharSequence scan, CharSequence status, CharSequence sex, Integer age, CharSequence location_name, CharSequence type) {
    this.eventId = eventId;
    this.timestamp = timestamp;
    this.tripId = tripId;
    this.userId = userId;
    this.qrId = qrId;
    this.scan = scan;
    this.status = status;
    this.sex = sex;
    this.age = age;
    this.location_name = location_name;
    this.type = type;
  }

  public SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return timestamp;
    case 2: return tripId;
    case 3: return userId;
    case 4: return qrId;
    case 5: return scan;
    case 6: return status;
    case 7: return sex;
    case 8: return age;
    case 9: return location_name;
    case 10: return type;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: eventId = (CharSequence)value$; break;
    case 1: timestamp = (Long)value$; break;
    case 2: tripId = (CharSequence)value$; break;
    case 3: userId = (CharSequence)value$; break;
    case 4: qrId = (CharSequence)value$; break;
    case 5: scan = (CharSequence)value$; break;
    case 6: status = (CharSequence)value$; break;
    case 7: sex = (CharSequence)value$; break;
    case 8: age = (Integer)value$; break;
    case 9: location_name = (CharSequence)value$; break;
    case 10: type = (CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'tripId' field.
   * @return The value of the 'tripId' field.
   */
  public CharSequence getTripId() {
    return tripId;
  }


  /**
   * Sets the value of the 'tripId' field.
   * @param value the value to set.
   */
  public void setTripId(CharSequence value) {
    this.tripId = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public CharSequence getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'qrId' field.
   * @return The value of the 'qrId' field.
   */
  public CharSequence getQrId() {
    return qrId;
  }


  /**
   * Sets the value of the 'qrId' field.
   * @param value the value to set.
   */
  public void setQrId(CharSequence value) {
    this.qrId = value;
  }

  /**
   * Gets the value of the 'scan' field.
   * @return The value of the 'scan' field.
   */
  public CharSequence getScan() {
    return scan;
  }


  /**
   * Sets the value of the 'scan' field.
   * @param value the value to set.
   */
  public void setScan(CharSequence value) {
    this.scan = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'sex' field.
   * @return The value of the 'sex' field.
   */
  public CharSequence getSex() {
    return sex;
  }


  /**
   * Sets the value of the 'sex' field.
   * @param value the value to set.
   */
  public void setSex(CharSequence value) {
    this.sex = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return The value of the 'age' field.
   */
  public int getAge() {
    return age;
  }


  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(int value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'location_name' field.
   * @return The value of the 'location_name' field.
   */
  public CharSequence getLocationName() {
    return location_name;
  }


  /**
   * Sets the value of the 'location_name' field.
   * @param value the value to set.
   */
  public void setLocationName(CharSequence value) {
    this.location_name = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public CharSequence getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(CharSequence value) {
    this.type = value;
  }

  /**
   * Creates a new TripEnrichment RecordBuilder.
   * @return A new TripEnrichment RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new TripEnrichment RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TripEnrichment RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new TripEnrichment RecordBuilder by copying an existing TripEnrichment instance.
   * @param other The existing instance to copy.
   * @return A new TripEnrichment RecordBuilder
   */
  public static Builder newBuilder(TripEnrichment other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for TripEnrichment instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TripEnrichment>
    implements org.apache.avro.data.RecordBuilder<TripEnrichment> {

    private CharSequence eventId;
    private long timestamp;
    private CharSequence tripId;
    private CharSequence userId;
    private CharSequence qrId;
    private CharSequence scan;
    private CharSequence status;
    private CharSequence sex;
    private int age;
    private CharSequence location_name;
    private CharSequence type;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.tripId)) {
        this.tripId = data().deepCopy(fields()[2].schema(), other.tripId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.userId)) {
        this.userId = data().deepCopy(fields()[3].schema(), other.userId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.qrId)) {
        this.qrId = data().deepCopy(fields()[4].schema(), other.qrId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.scan)) {
        this.scan = data().deepCopy(fields()[5].schema(), other.scan);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.status)) {
        this.status = data().deepCopy(fields()[6].schema(), other.status);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.sex)) {
        this.sex = data().deepCopy(fields()[7].schema(), other.sex);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.age)) {
        this.age = data().deepCopy(fields()[8].schema(), other.age);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.location_name)) {
        this.location_name = data().deepCopy(fields()[9].schema(), other.location_name);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.type)) {
        this.type = data().deepCopy(fields()[10].schema(), other.type);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing TripEnrichment instance
     * @param other The existing instance to copy.
     */
    private Builder(TripEnrichment other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tripId)) {
        this.tripId = data().deepCopy(fields()[2].schema(), other.tripId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.userId)) {
        this.userId = data().deepCopy(fields()[3].schema(), other.userId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.qrId)) {
        this.qrId = data().deepCopy(fields()[4].schema(), other.qrId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.scan)) {
        this.scan = data().deepCopy(fields()[5].schema(), other.scan);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.status)) {
        this.status = data().deepCopy(fields()[6].schema(), other.status);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.sex)) {
        this.sex = data().deepCopy(fields()[7].schema(), other.sex);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.age)) {
        this.age = data().deepCopy(fields()[8].schema(), other.age);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.location_name)) {
        this.location_name = data().deepCopy(fields()[9].schema(), other.location_name);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.type)) {
        this.type = data().deepCopy(fields()[10].schema(), other.type);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public Builder setEventId(CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'tripId' field.
      * @return The value.
      */
    public CharSequence getTripId() {
      return tripId;
    }


    /**
      * Sets the value of the 'tripId' field.
      * @param value The value of 'tripId'.
      * @return This builder.
      */
    public Builder setTripId(CharSequence value) {
      validate(fields()[2], value);
      this.tripId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'tripId' field has been set.
      * @return True if the 'tripId' field has been set, false otherwise.
      */
    public boolean hasTripId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'tripId' field.
      * @return This builder.
      */
    public Builder clearTripId() {
      tripId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public CharSequence getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public Builder setUserId(CharSequence value) {
      validate(fields()[3], value);
      this.userId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public Builder clearUserId() {
      userId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'qrId' field.
      * @return The value.
      */
    public CharSequence getQrId() {
      return qrId;
    }


    /**
      * Sets the value of the 'qrId' field.
      * @param value The value of 'qrId'.
      * @return This builder.
      */
    public Builder setQrId(CharSequence value) {
      validate(fields()[4], value);
      this.qrId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'qrId' field has been set.
      * @return True if the 'qrId' field has been set, false otherwise.
      */
    public boolean hasQrId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'qrId' field.
      * @return This builder.
      */
    public Builder clearQrId() {
      qrId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'scan' field.
      * @return The value.
      */
    public CharSequence getScan() {
      return scan;
    }


    /**
      * Sets the value of the 'scan' field.
      * @param value The value of 'scan'.
      * @return This builder.
      */
    public Builder setScan(CharSequence value) {
      validate(fields()[5], value);
      this.scan = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'scan' field has been set.
      * @return True if the 'scan' field has been set, false otherwise.
      */
    public boolean hasScan() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'scan' field.
      * @return This builder.
      */
    public Builder clearScan() {
      scan = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public Builder setStatus(CharSequence value) {
      validate(fields()[6], value);
      this.status = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public Builder clearStatus() {
      status = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'sex' field.
      * @return The value.
      */
    public CharSequence getSex() {
      return sex;
    }


    /**
      * Sets the value of the 'sex' field.
      * @param value The value of 'sex'.
      * @return This builder.
      */
    public Builder setSex(CharSequence value) {
      validate(fields()[7], value);
      this.sex = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'sex' field has been set.
      * @return True if the 'sex' field has been set, false otherwise.
      */
    public boolean hasSex() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'sex' field.
      * @return This builder.
      */
    public Builder clearSex() {
      sex = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * @return The value.
      */
    public int getAge() {
      return age;
    }


    /**
      * Sets the value of the 'age' field.
      * @param value The value of 'age'.
      * @return This builder.
      */
    public Builder setAge(int value) {
      validate(fields()[8], value);
      this.age = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'age' field.
      * @return This builder.
      */
    public Builder clearAge() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'location_name' field.
      * @return The value.
      */
    public CharSequence getLocationName() {
      return location_name;
    }


    /**
      * Sets the value of the 'location_name' field.
      * @param value The value of 'location_name'.
      * @return This builder.
      */
    public Builder setLocationName(CharSequence value) {
      validate(fields()[9], value);
      this.location_name = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'location_name' field has been set.
      * @return True if the 'location_name' field has been set, false otherwise.
      */
    public boolean hasLocationName() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'location_name' field.
      * @return This builder.
      */
    public Builder clearLocationName() {
      location_name = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public CharSequence getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public Builder setType(CharSequence value) {
      validate(fields()[10], value);
      this.type = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public Builder clearType() {
      type = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TripEnrichment build() {
      try {
        TripEnrichment record = new TripEnrichment();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (Long) defaultValue(fields()[1]);
        record.tripId = fieldSetFlags()[2] ? this.tripId : (CharSequence) defaultValue(fields()[2]);
        record.userId = fieldSetFlags()[3] ? this.userId : (CharSequence) defaultValue(fields()[3]);
        record.qrId = fieldSetFlags()[4] ? this.qrId : (CharSequence) defaultValue(fields()[4]);
        record.scan = fieldSetFlags()[5] ? this.scan : (CharSequence) defaultValue(fields()[5]);
        record.status = fieldSetFlags()[6] ? this.status : (CharSequence) defaultValue(fields()[6]);
        record.sex = fieldSetFlags()[7] ? this.sex : (CharSequence) defaultValue(fields()[7]);
        record.age = fieldSetFlags()[8] ? this.age : (Integer) defaultValue(fields()[8]);
        record.location_name = fieldSetFlags()[9] ? this.location_name : (CharSequence) defaultValue(fields()[9]);
        record.type = fieldSetFlags()[10] ? this.type : (CharSequence) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TripEnrichment>
    WRITER$ = (org.apache.avro.io.DatumWriter<TripEnrichment>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TripEnrichment>
    READER$ = (org.apache.avro.io.DatumReader<TripEnrichment>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeLong(this.timestamp);

    out.writeString(this.tripId);

    out.writeString(this.userId);

    out.writeString(this.qrId);

    out.writeString(this.scan);

    out.writeString(this.status);

    out.writeString(this.sex);

    out.writeInt(this.age);

    out.writeString(this.location_name);

    out.writeString(this.type);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);

      this.timestamp = in.readLong();

      this.tripId = in.readString(this.tripId instanceof Utf8 ? (Utf8)this.tripId : null);

      this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);

      this.qrId = in.readString(this.qrId instanceof Utf8 ? (Utf8)this.qrId : null);

      this.scan = in.readString(this.scan instanceof Utf8 ? (Utf8)this.scan : null);

      this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);

      this.sex = in.readString(this.sex instanceof Utf8 ? (Utf8)this.sex : null);

      this.age = in.readInt();

      this.location_name = in.readString(this.location_name instanceof Utf8 ? (Utf8)this.location_name : null);

      this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);

    } else {
      for (int i = 0; i < 11; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.tripId = in.readString(this.tripId instanceof Utf8 ? (Utf8)this.tripId : null);
          break;

        case 3:
          this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);
          break;

        case 4:
          this.qrId = in.readString(this.qrId instanceof Utf8 ? (Utf8)this.qrId : null);
          break;

        case 5:
          this.scan = in.readString(this.scan instanceof Utf8 ? (Utf8)this.scan : null);
          break;

        case 6:
          this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
          break;

        case 7:
          this.sex = in.readString(this.sex instanceof Utf8 ? (Utf8)this.sex : null);
          break;

        case 8:
          this.age = in.readInt();
          break;

        case 9:
          this.location_name = in.readString(this.location_name instanceof Utf8 ? (Utf8)this.location_name : null);
          break;

        case 10:
          this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










